import plotly.graph_objects as go
import plotly.io as pio

pio.templates["master"] = go.layout.Template(
    data = {
        'bar': [{'marker': {'line': {'color': '#222222', 'width': 0.5}}, 'type': 'bar'}]
    },
    layout = {'annotationdefaults': {'arrowcolor': '#2a3f5f',
                                      'arrowhead': 0,
                                      'arrowwidth': 1,
                                      'bgcolor': '#faf8f0',
                                      'borderpad': 8,
                                      'font': {'color': '#000000', 'size': 12},
                                      'showarrow': False,
                                      'x': 2.5,
                                      'y': 5},
               'autotypenumbers': 'strict',
               'coloraxis': {'colorbar': {'outlinewidth': 1, 'tickcolor': '#000000', 'ticks': 'outside'}},
               'colorscale': {'diverging': [[0, '#8e0152'], [0.1, '#c51b7d'],
                                            [0.2, '#de77ae'], [0.3, '#f1b6da'],
                                            [0.4, '#fde0ef'], [0.5, '#f7f7f7'],
                                            [0.6, '#e6f5d0'], [0.7, '#b8e186'],
                                            [0.8, '#7fbc41'], [0.9, '#4d9221'], [1,
                                            '#276419']],
                              'sequential': [[0.0, '#0d0887'],
                                             [0.1111111111111111, '#46039f'],
                                             [0.2222222222222222, '#7201a8'],
                                             [0.3333333333333333, '#9c179e'],
                                             [0.4444444444444444, '#bd3786'],
                                             [0.5555555555555556, '#d8576b'],
                                             [0.6666666666666666, '#ed7953'],
                                             [0.7777777777777778, '#fb9f3a'],
                                             [0.8888888888888888, '#fdca26'], [1.0,
                                             '#f0f921']],
                              'sequentialminus': [[0.0, '#0d0887'],
                                                  [0.1111111111111111, '#46039f'],
                                                  [0.2222222222222222, '#7201a8'],
                                                  [0.3333333333333333, '#9c179e'],
                                                  [0.4444444444444444, '#bd3786'],
                                                  [0.5555555555555556, '#d8576b'],
                                                  [0.6666666666666666, '#ed7953'],
                                                  [0.7777777777777778, '#fb9f3a'],
                                                  [0.8888888888888888, '#fdca26'],
                                                  [1.0, '#f0f921']]},
               'colorway': ['#005288', '#1C4C38', '#01B2B3', '#DD663C', '#A899A5', '#d8eded', '#492a42', '#bdd7e5'],
               'font': {'color': '#000000'},
               'geo': {'bgcolor': 'white',
                       'lakecolor': 'white',
                       'landcolor': '#E5ECF6',
                       'showlakes': True,
                       'showland': True,
                       'subunitcolor': 'white'},
               'height': 400,
               'hoverlabel': {'align': 'left'},
               'hovermode': 'closest',
               'mapbox': {'style': 'light'},
               'margin': {'b': 10, 'l': 10, 'r': 10, 't': 50},
               'paper_bgcolor': '#faf8f0',
               'plot_bgcolor': '#faf8f0',
               'polar': {'angularaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
                         'bgcolor': '#E5ECF6',
                         'radialaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''}},
               'scene': {'xaxis': {'backgroundcolor': '#E5ECF6',
                                   'gridcolor': 'white',
                                   'gridwidth': 2,
                                   'linecolor': 'white',
                                   'showbackground': True,
                                   'ticks': '',
                                   'zerolinecolor': 'white'},
                         'yaxis': {'backgroundcolor': '#E5ECF6',
                                   'gridcolor': 'white',
                                   'gridwidth': 2,
                                   'linecolor': 'white',
                                   'showbackground': True,
                                   'ticks': '',
                                   'zerolinecolor': 'white'},
                         'zaxis': {'backgroundcolor': '#E5ECF6',
                                   'gridcolor': 'white',
                                   'gridwidth': 2,
                                   'linecolor': 'white',
                                   'showbackground': True,
                                   'ticks': '',
                                   'zerolinecolor': 'white'}},
               'shapedefaults': {'line': {'color': '#000000', 'width': 1},
                                 'type': 'line',
                                 'x0': 1,
                                 'x1': 4,
                                 'y0': 5,
                                 'y1': 5},
               'showlegend': True,
               'ternary': {'aaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
                           'baxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
                           'bgcolor': '#E5ECF6',
                           'caxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''}},
               'title': {'x': 0.05},
               'width': 800,
               'xaxis': {'automargin': True,
                         'gridcolor': 'white',
                         'linecolor': 'black',
                         'linewidth': 1,
                         'showgrid': False,
                         'showline': True,
                         'tickfont': {'color': '#000000', 'family': 'Arial', 'size': 12},
                         'ticks': '',
                         'title': {'standoff': 15},
                         'zerolinecolor': 'black',
                         'zerolinewidth': 1},
               'yaxis': {'automargin': True,
                         'gridcolor': 'white',
                         'linecolor': 'black',
                         'linewidth': 1,
                         'showgrid': False,
                         'showline': True,
                         'tickfont': {'color': '#000000', 'family': 'Arial', 'size': 12},
                         'ticks': '',
                         'title': {'standoff': 15},
                         'zerolinecolor': 'black',
                         'zerolinewidth': 1}}
)